config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => "orders#new"

  resources :orders, only: [:new, :create]
  resources :charges, only: [:new, :create]
    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :orders
end

app/models/order.rb
class Order < ApplicationRecord

  has_many :books
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  rescue_from Stripe::CardError, with: :catch_exception
  before_action :find_order, only: [:new, :create]
  
  def new
    
  end

  def create
    user = User.first
    StripeChargesServices.new(charges_params, user).call
    redirect_to new_charge_path(order_id: @order)
  end

  private

  def find_order
    @order = Order.find(params[:order_id])
  end

  def charges_params
    params.permit(:stripeEmail, :stripeToken, :order_id)
  end

  def catch_exception(exception)
    flash[:error] = exception.message
  end
  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def new
    @order = Order.new
    @books = Book.order(:title)
  end

  def create
    @order = Order.new
    book = Book.find(params[:book_id])
    @order.books_id = book.id
    @order.amount = book.price
    if @order.save
      redirect_to new_charge_path(order_id: @order)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/charges/new.html.erb
<h1>Make Payment</h1>
<%= form_tag charges_path do %>
  <%= hidden_field_tag(:order_id, @order.id) %>
  <article>
    <% if flash[:error].present? %>
    <div id="error_explanation">
      <p><%= flash[:error] %></p>
    </div>
    <% end %>
    <label class="amount">
    <span>Amount: $<%= @order.amount %></span>
    </label>
  </article>
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-description="A month's subscription"
    data-amount="<%= @order.amount %>"
    data-locale="auto"></script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PaymentGateway</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/_book_list.html.erb
<div class="row">
	 <div class="col-md-3">
	 		<%= book.title %>
	 </div>
	 <div class="col-md-3">
	 		<%= book.author %>
	 </div>
	 <div class="col-md-3">
	 		<%= book.price %>
	 </div>
	 <div>
	 	<%= form_for @order do 	|f| %>
	 		<%= hidden_field_tag(:book_id, book.id) %>
	 		<%= f.submit "Order", class: "btn btn-primary" %>
	 	<% end %>
	 </div>
</div>

app/views/orders/new.html.erb
<h1>Place Your Orders</h1>
<div class="row">
	<div class="col-md-3"><h1>Title</h1></div>
	<div class="col-md-3"><h1>Author</h1></div>
	<div class="col-md-3"><h1>Amount</h1></div>
</div>
<div class="book-list">
	<%= render partial: 'book_list', collection: @books, as: :book %>
</div>